#!/bin/sh

PORT_LIST=$(cat - | xargs -n1)
if [ "$PORT_LIST" ]; then
	for port in $PORT_LIST; do
		port_name=$(echo "$port" | cut -d/ -f 2)
		port_category=$(echo "$port" | cut -d/ -f 1)
		yes | glport -u -p "$port_name" -c "$port_category"
	done
else
	cat << EOF
usage: $(basename $0) [ports]
EOF
fi
